server:
  port: 8761
spring:
  application:
    name: service-registry 
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    prometheus:
      metrics:
        export:
          enabled: true