global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flat-service'
    static_configs:
      - targets: ['localhost:8082']

  - job_name: 'heating-service'
    static_configs:
      - targets: ['localhost:8083']

  - job_name: 'recommendation-service'
    static_configs:
      - targets: ['localhost:8085']
  - job_name: 'statistics-service'
    static_configs:
      - targets: ['localhost:8084']
  - job_name: 'user-service'
    static_configs:
      - targets: ['localhost:8081']