server:
  port: 8085
spring:
  application:
    name: recommendation-service 
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    prometheus:
      metrics:
        export:
          enabled: true