server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: flat-service
          uri: lb://flat-service
          predicates:
            - Path=/api/flats/**
        - id: heating-service
          uri: lb://heating-service
          predicates:
            - Path=/api/heating/**
        - id: statistics-service
          uri: lb://statistics-service
          predicates:
            - Path=/api/statistics/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/api/recommendations/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true 